/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ReproComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLReproComponentElement extends Components.ReproComponent, HTMLStencilElement {
    }
    var HTMLReproComponentElement: {
        prototype: HTMLReproComponentElement;
        new (): HTMLReproComponentElement;
    };
    interface HTMLElementTagNameMap {
        "repro-component": HTMLReproComponentElement;
    }
}
declare namespace LocalJSX {
    interface ReproComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "repro-component": ReproComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "repro-component": LocalJSX.ReproComponent & JSXBase.HTMLAttributes<HTMLReproComponentElement>;
        }
    }
}
